### ISSUE TITLE
Conflicting shard name

### ISSUE THREAD

**Issue by rmarronnier** [stefanwille/crystal-redis#136]
https://github.com/cable-cr/cable/issues/74 brought me here :
The following shard.yml triggers an error : 
```yml
dependencies:
  redis:
    github: jgaskins/redis
  mosquito:
    github: hugopl/sidekiq.cr
```

Because the sidekiq shard has
```yml
dependencies:
  redis:
    github: stefanwille/crystal-redis
    version: ">= 2.6"
```

One solution would be to change the name `redis` to something else in https://github.com/stefanwille/crystal-redis/blob/5fc089cc4f73f08eb42170cb82e30205369a18ad/shard.yml#L1

I'm posting the 'mirror' issue in https://github.com/jgaskins/redis
